name: Rust-Test

on:
  push:
    branches: [ "main" ]
    paths:
      - crates/
  pull_request:
    branches: [ "main" ]
    paths:
      - crates/
  workflow_call:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
